const routes = {
    //Packaging-GIN Release Routes://New packing APIs
    quoteItemsInfo: "packing-getQuoteLineCreationInfo",
    insertQuoteItem: "packing-insertQuoteLineItemDetail",
    getAllPackingRequests: 'packing-getAllPackingRequests',
    viewPackingRequest: 'packing-viewPackingRequest',
    requestNewPackType: 'packing-requestNewPackType',
    approveNewPackType: 'packing-approveNewPackType',
    rejectNewPackType: 'packing-rejectNewPackType',
    //--------
    login: "qa-testenvLogin",
    forget: "qa-forgotPassword",
    confirmForgotPassword: "qa-confirmForgotPassword",
    registerUser: "qa-userRegistration",
    insertUser: "qa-insertUserDetails",
    // Crqa-eatedUser:"createdSupplier",
    listPoolUsers: "qa-listPoolUsers",
    // usqa-erStatus: "userStatus",
    userStatus: "qa-enableUser",
    userStatusDisable: "qa-disableUser",
    changePassword: "qa-changePassword",
    // leqa-ads: "getAllLeads",
    leads: "getLeadsInfo",  
    accounts: "getAllAccounts",
    contacts: "getAllContacts",
    quotes: "getAllQuotes",
    userRole: "qa-getUserRole",
    userDetail: "getUserDetail",
    userAllDetail: "qa-getAllUsersDetail",
    companyName: "qa-getCompanyNames",
    designation: "qa-getDesignation",
    departmentName: "qa-getDepartmentNames",
    division: "qa-getDivisions",
    delegatedApprover: "qa-getDelegatedApprover",
    country: "getCountry",
    state: "getState",
    city: "getCity",
    profile: "qa-getUserProfile",
    insertLead: "qa-insertLeadDetails",
    leadsInfo: "qa-getLeadCreationInfo",
    leadsDetail: "qa-getLeadDetailonHyperLink",
    contactsInleadToAccount: "qa-getContactsInLeadtoAcc",
    convertLeadToAccount: "insertLeadIntoAccount",
    getUsers: "getUsers",
    quotesInfo: "getQuotationCreationInfo",
    insertQuote: "qa-insertQuotationDetail",
    sampleRequests: "getAllSampleRequests",
    accountsDetail: "getAccountHyperlink",
    accountContact: "cvuAccountContactDetails",
    accountSample: "qa-cvuSampleRequest",
    insertSample: "insertOrUpdateSampleRequest",
    viewSample: "viewSampleRequest",
    getQuoteItems: "dev-getAllQuoteLineItems",
    updateQuoteItem: "dev-updateQuoteLineInfo",
    updateQuoteStatus: "dev-updateQuotationStatus",
    getAccountContacts: "getAccountContacts",
    getAccountSamples: "getAccountSamples",
    getAccountQuotes: "getAccountQuotes",
    reassignLead: "dev-reassignLead",
    reassignAccount: "reassignAccount",
    quotesInfoErp: "qa-getQuoteInformation",
    quoteItemSystemInfo: "qa-qqiSystemMasterInfo",
    quoteItemSystemPackInfo: "qa-qqiSamplePackDetails",
    quoteRequestPrice: "qa-quotationPriceRequest",
    quoteSamples: "qa-qqiSampleGCConfig",
    quoteSamplePricing: "qa-updateQuotePricingInfo",
    quoteRequestGCRates: "qa-reqForGcRates",
    currencyConversion: "qa-qqiCurrencyStamp",
    poCreationInfo: "qa-getPOFormInfo",
    PoCreationInfo: "qa-getPoCreationInfo",
    getAllPurchaseOrders: "listPurchaseOrders",
    createGCPo: "qa-insertGCPODetails",
    approvedQuotesOnGC: "qa-listApprovedQtLinesOnGc",
    topApprovedPos: "qa-listTop3ApprovedPos",
    topMrin: "qa-topMrinDetail",
    poDetails: "qa-viewGCPODetails",
    portAndOriginForPo: "qa-getPortandOriginForPO",
    poDocuments: "qa-poDocumentsUpload",
    updateGCPo: "qa-editGCPODetails",
    gCPoStatus: "qa-updateGcPoStatus",
    getProductAndCategory: "getcreateSRItemForm",
    createVendor: "qa-insertVendorGCPO",
    //mriqa-n
    getAllmrins: 'listMrins',
    mrinDetails: 'qa-viewMrin',
    createOrUpdateMrin: 'qa-insertOrUpdateMrin',
    // enqa-tity and po details
    getMrinCreationInfo: 'getMrinCreationInfo',
    // mrqa-in list for po
    getMrinListForPoView: 'qa-getMrinListForPoView',
    // Gcqa-s
    getGCs: 'listGCDetails',
    getGCDetail: 'viewGCDetail',
    // Suqa-pplier
    getSuppliers: 'qa-getSuppliers',
    getSupplierList: 'listSuppliers',
    editSuppliers: 'qa-editSupplier',
    curdSupplier: 'cvuSupplier',
    getGcCreationInfo: 'getGCCreationInfo',
    createOrUpdateGcDetail: 'qa-insertOrEditGCDetail',
    vendorLogin: 'qa-vendorLogin',
    getDispatchDetails: 'qa-viewGCPODispatchDetails',
    updateGCPoDispatch: "qa-editGCPODispatchDetails",
    deleteGCPOAutoDispatch: 'qa-deleteGCPOAutoDispatch',
    balQuoteQtyForPoOrder: 'qa-getBalQuoteQtyForPoOrder',
    getGCDebitNoteCreationInfo: 'qa-getGCDebitNoteCreationInfo',
    listGCDebitNoteDetails: 'listGCDebitNoteDetails',
    insertOrEditGCDebitNoteDetail: 'qa-insertOrEditGCDebitNoteDetail',
    viewGCDebitNoteDetail: 'qa-viewGCDebitNoteDetail',
    updateGcDebitNoteStatus: 'qa-updateGcDebitNoteStatus',
    createorupdateSampleLineItem: 'insertOrUpdateSampleLineItem',
    getNotifications: 'getNotifications',
    viewAndDeleteSampleLineItem: 'viewAndDeleteSampleLineItem',
    updateMRINGCSpec: 'qa-updateMRINGCSpec',
    sendEmail: 'qa-sendITSupportEmail',
    releaseDebitNote: 'qa-releaseDebitNote',
    taxMaster: 'qa-cvu_Tax_Master',
    taxList: 'qa-list_Tax_Grid',



    getConversatioRatio: 'getConversatioRatio',
    getSamplesInfo: 'getSamplesInfo',
    getSelectedSamplesForPricing: 'getSelectedSamplesForPricing',
    updateQuotationStatusForPricing: 'updateQuotationStatusForPricing',
    updateGcPriceOnQuotes: 'updateGcPriceOnQuotes',
    getOtherFactorsInfo: 'getOtherFactorsInfo',
    updateOtherFactorsInfo: 'updateOtherFactorsInfo',
    updateSamplesInfoForPricing: 'updateSamplesInfoForPricing',
    getPackingInfoForPricing: 'getPackingInfoForPricing',
    getFinalisedSamples: 'getFinalisedSamples',
    updateConfirmSample: 'updateConfirmSample',
    insertPricingInfo: 'insertPricingInfo',
    getGCDataOnQuotes: 'getGCDataOnQuotes',
}

export default routes;
